version: '3.1'

services:
  mongo:
    image: mongo
    container_name: microsub-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
  mongo-express:
    image: mongo-express
    container_name: microsub-mongo-express
    ports:
      - "8082:8081"
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
